### ISSUE TITLE
sir,依赖包能给么。：））

### ISSUE THREAD

**Issue by aaq1adqwe** [pacemrc/VulDebug#1]
sir,依赖包能给么。：））

**Comment by pacemrc** [comment]
可以的 我晚点把依赖包也commit



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年1月18日(周四) 中午11:34
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [pacemrc/VulDebug] sir,依赖包能给么。：）） (Issue #1)




 
sir,依赖包能给么。：））

**Comment by pacemrc** [comment]
已上传依赖包
